### PR TITLE
Make Express static serving configurable

### PR DESCRIPTION
**Pull request by arjansingh**
Express allows you to configure parameters when you serve static assets: https://expressjs.com/en/4x/api.html#express

For example, you can set `maxAge` on the request so the browser knows to cache the asset.

This PR allows these options to be made configurable.

### CODE REVIEW

**Comment by arjansingh** [comment]
Node `0.12` is failing. I can install an `Object.assign` polyfill for it. Please advise.

**Comment by arjansingh** [comment]
I'll also remove node 0.12 support since it's EOL in the New Year.

**Comment by briangonzalez** [comment]
@tomdale @arjansingh 

What's the likelihood of this one landing any time soon? Relying on fork is starting to cause some headache.

**Comment by arjansingh** [comment]
Depends on #43

**Comment by mirague** [comment]
#43 is closed, what's the status here?

**Comment by tomdale** [comment]
@mirague Generally speaking, we should avoid duplicating the Express API because it couples us to one particular version and makes upgrading in the future harder. If you need to customize how static assets get served, the `preMiddleware`/`postMiddleware` hooks and (worst case) pluggable `httpServer` should do the job.

**Comment by arjansingh** [comment]
@tomdale Didn't realize this was still open. We do not need it anymore. Any objections to closing it?

**Comment by arjansingh** [comment]
Cleaning up old PRs I made. Closing this.

**Pull request closed without merging**
