### PR TITLE
Allow to enable Basic Authentication from FastBoot App Server

### PR DESCRIPTION
**Pull request by bobisjan**

### CODE REVIEW

**Comment by danmcclain** [comment]
This should be handled be the combination of the following, please correct me if I'm wrong

https://github.com/ember-fastboot/fastboot-app-server/blob/master/src/express-http-server.js#L14-L15
and 
https://github.com/ember-fastboot/fastboot-app-server/blob/master/src/express-http-server.js#L37

Which utilize:
https://github.com/ember-fastboot/fastboot-app-server/blob/master/src/basic-auth.js

**Comment by bobisjan** [comment]
Yes, I should use better words for PR title - this change allows to pass `username` and `password` directly into `FastBootAppServer` without the need to manually create the `ExpressHTTPServer` (like `gzip` option).

**Comment by danmcclain** [comment]
Ah, ok, I see it now. Can you rebase please?

**Comment by bobisjan** [comment]
✅

**Comment by tomdale** [comment]
@bobisjan Hey Jan, thanks for rebasing. It looks like the tests are failing due to a syntax error. Would you mind looking into it?

Also, while I have you here, would you mind updating the README as well to cover this functionality. I want to make sure the docs keep up to date with the implementation. 😄

**Comment by bobisjan** [comment]
@tomdale, fixed "rebase" error.

`README.md` should be already updated, 👀 https://github.com/ember-fastboot/fastboot-app-server/pull/26/files#diff-04c6e90faac2675aa89e2176d2eec7d8.

**Comment by tomdale** [comment]
👍

**Pull request merged**
