### PR TITLE
Support custom cache control headers for static assets

### PR DESCRIPTION
**Pull request by sivakumar-kailasam**
Allows users to configure cache control for the static assets. Addresses #41

### CODE REVIEW

**Comment by sivakumar-kailasam** [comment]
Another alternative could be passing an instance of https://github.com/expressjs/serve-static

**Comment by dbbk** [comment]
Would love to get this in, I'd like my assets to be immutable rather than max-age=0. What is needed to get merged?

**Comment by mirague** [comment]
Same here, `max-age=0` makes no sense for static assets.

**Comment by mirague** [comment]
Same here, `max-age=0` makes no sense for static assets.

Also, possible duplicate of #35

**Comment by sivakumar-kailasam** [comment]
Shucks, looks like #35 is much more flexible than this one, I can either improve or close this one in favor of it. Thoughts @arjansingh ?

**Pull request closed without merging**
