### PR TITLE
expose sandboxGlobals option via FastBootAppServer

### PR DESCRIPTION
**Pull request by marcoow**
This adds the `sandboxGlobals` option to `FastBootAppServer` so that globals can be passed into the sandbox and thus the Ember app when the server is created (e.g. a `Raven` object for Sentry).

### CODE REVIEW

**Comment by kratiahuja** [comment]
@marcoow would you mind updating the readme?

**Comment by marcoow** [comment]
@kratiahuja: done

**Comment by kratiahuja** [comment]
@marcoow LGTM.

**Comment by kratiahuja** [comment]
@marcoow Apologies for the delay in the release. This completely slipped out of my mind. `fastboot-app-server@1.0.2` is published.

**Pull request merged**
