### PR TITLE
404 handling under `/assets/`

### PR DESCRIPTION
**Pull request by pwfisher**
- send actual HTTP 404, do not execute FastBoot App

### CODE REVIEW

**Comment by tomdale** [comment]
@pwfisher Can you add a small test to verify that hitting anything in the `/assets/` path returns a 404?

**Comment by arjansingh** [comment]
I'll look into adding a test for him.

**Comment by arjansingh** [comment]
Tests for this are added in #25

**Comment by tomdale** [comment]
Closed in favor of #25.

**Pull request closed without merging**
